plugins {
    id 'fabric-loom' version '1.15.5'
    id 'maven-publish'
    id("org.jetbrains.kotlin.jvm") version "2.1.20"
}

dev.builder.BuildHelper.configureIdentity(project)
dev.builder.BuildHelper.configureRepositories(project)
dev.builder.BuildHelper.createDependencyBuckets(project)
dev.builder.BuildHelper.configureDependencies(project)
dev.builder.BuildHelper.configureJava(project, dev.builder.MetaLibs.TARGET_JAVA_VERSION)
dev.builder.BuildHelper.configureJar(project)
dev.builder.BuildHelper.configurePublishing(project)
dev.builder.BuildTalks.attach(project)

loom {
    accessWidenerPath = dev.builder.BuildHelper.accessWidener(project)
}

publishing.repositories {}
